@GenericRepositoryPatternWebAPI_http_HostAddress = http://localhost:5117
@GenericRepositoryPatternWebAPI_https_HostAddress = https://localhost:7195

### registering http weatherforecast
GET {{GenericRepositoryPatternWebAPI_http_HostAddress}}/weatherforecast/
Accept: application/json

### registering https weatherforecast
GET {{GenericRepositoryPatternWebAPI_https_HostAddress}}/weatherforecast/
Accept: application/json

### registering http person
GET {{GenericRepositoryPatternWebAPI_http_HostAddress}}/person/
Accept: application/json

### registering https person
GET {{GenericRepositoryPatternWebAPI_https_HostAddress}}/person/
Accept: application/json